# Generated by Django 5.0.7 on 2025-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_emailtemplate_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AddField(
            model_name='subscribers',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
