# Generated by Django 5.0.7 on 2025-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_subscribers_options_subscribers_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='unsubscribed_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
