# Generated by Django 5.0.7 on 2025-08-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlog',
            name='description',
        ),
    ]
