# Generated by Django 5.0.6 on 2024-10-24 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='ArticleVlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_vlog', to='blog.article')),
            ],
            options={
                'unique_together': {('article', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='LikeVlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_vlog', to='blog.vlog')),
            ],
            options={
                'unique_together': {('vlog', 'ip_address')},
            },
        ),
    ]
