# Generated by Django 5.0.6 on 2024-10-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_options_articlevlog_likevlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleVlog',
            new_name='LikeArticle',
        ),
        migrations.AlterField(
            model_name='vlog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlogs', to='blog.category'),
        ),
    ]
