# Generated by Django 5.0.7 on 2024-12-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_articlevlog_likearticle_alter_vlog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_slug',
        ),
        migrations.DeleteModel(
            name='RepliedComment',
        ),
    ]
