# Generated by Django 5.0.7 on 2024-12-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subscriber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likevlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likevlog',
            name='vlog',
        ),
        migrations.DeleteModel(
            name='LikeArticle',
        ),
        migrations.DeleteModel(
            name='LikeVlog',
        ),
    ]
