# Generated by Django 5.0.7 on 2025-01-03 17:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_vlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
